#!/bin/sh
rm -f libcnp.so
g++ -m64 -shared -fPIC -std=c++20 libcnp.cc -o libcnp.so -I/usr/local/include/highs -Wl,-soname,libcnp.so -Wl,-rpath,/usr/local/lib64 -L/usr/local/lib64 -lpthread -lm -lz -ldl -lhighs -O4 -Wall
